# Generated by Django 4.0.5 on 2022-06-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='title',
        ),
    ]
