# Generated by Django 4.0.5 on 2022-06-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0010_alter_customer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
