# Generated by Django 4.1.7 on 2023-04-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0012_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
